# Generated by Django 4.0.4 on 2022-08-24 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaudiArabiaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedStateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='reports_management_app.tag')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_report_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedStateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('video', models.FileField(upload_to='UnitedStateVideos/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_report_video', to='reports_management_app.unitedstatereport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_Video_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedStateReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed on the report type', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_report_editor', to=settings.AUTH_USER_MODEL)),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_report', to='reports_management_app.unitedstatereport')),
            ],
        ),
        migrations.CreateModel(
            name='UnitedStateImge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('img', models.ImageField(upload_to='UnitedStateImages/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_report_img', to='reports_management_app.unitedstatereport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_img_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedStateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('document', models.FileField(upload_to='UnitedStateDocuments/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_report_doc', to='reports_management_app.unitedstatereport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='US_doc_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaudiArabiaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('video', models.FileField(upload_to='SaudiArabiaVideos/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_report_video', to='reports_management_app.saudiarabiareport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_Video_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaudiArabiaReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed on the report type', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_report_editor', to=settings.AUTH_USER_MODEL)),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_report', to='reports_management_app.saudiarabiareport')),
            ],
        ),
        migrations.AddField(
            model_name='saudiarabiareport',
            name='tags',
            field=models.ManyToManyField(to='reports_management_app.tag'),
        ),
        migrations.AddField(
            model_name='saudiarabiareport',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_report_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SaudiArabiaImge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('img', models.ImageField(upload_to='SaudiArabiaImages/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_report_img', to='reports_management_app.saudiarabiareport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_img_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaudiArabiaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('document', models.FileField(upload_to='SaudiArabiaDocuments/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_report_doc', to='reports_management_app.saudiarabiareport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KSA_doc_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('video', models.FileField(upload_to='GeneralVideos/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_report_video', to='reports_management_app.unitedstatereport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_Video_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed on the report type', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_report_editor', to=settings.AUTH_USER_MODEL)),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_report', to='reports_management_app.generalreport')),
            ],
        ),
        migrations.AddField(
            model_name='generalreport',
            name='tags',
            field=models.ManyToManyField(to='reports_management_app.tag'),
        ),
        migrations.AddField(
            model_name='generalreport',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_report_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GeneralImge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('img', models.ImageField(upload_to='GeneralImages/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_report_img', to='reports_management_app.generalreport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_img_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('document', models.FileField(upload_to='GeneralDocuments/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_report_doc', to='reports_management_app.generalreport')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='G_doc_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
